name: CI

on:
  push:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Install dependencies
        run: python -m pip install jupyterlab
      - name: Build the extension
        run: |
          jlpm
          cd test-jlab-toastify
          jlpm install
          jlpm remove jupyterlab_toastify
          jlpm add file:${PWD}/..
          jupyter labextension install .
          python -m jupyterlab.browser_check
